name: Concrete pre-commit and post-push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: CMake config
      run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
    - name: CMake build
      run: cmake --build build
    - name: CMake test
      run: cmake --build build --target test